server:
  port: ${SERVER_PORT:8082}
  http2:
    enabled: true
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024


#Logs
logging:
  level:
    ROOT: ${LOG_ROOT_LEVEL:INFO}
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: ${LOG_REQUEST_LEVEL:DEBUG}
  request-payload:
    enabled: ${LOG_REQUEST_ENABLED:true}
    max-payload-length: ${LOG_REQUEST_MAX_PAYLOAD_LENGTH:1000}

spring:
  application:
    name: scrap-product-service
  data:
    mongodb:
      uri: ${MONGO_CONNECTION_STRING:mongodb://localhost:27017}
      database: ${MONGO_DATABASE_NAME:Products}

# Swagger configurations
swaggerBaseUrl: ${SWAGGER_BASE_URL:localhost:${server.port}}

threadPoolSize: ${BUSINESS_RULE_THREAD_POOL_SIZE:4}

service:
  timeout: ${TIMEOUT_REQUEST_SERVICE:2000}