server:
  port: ${SERVER_PORT:8082}
  http2:
    enabled: true

#Logs
logging:
  level:
    ROOT: ${LOG_ROOT_LEVEL:INFO}

spring:
  application:
    name: scrap-product-service
  data:
    mongodb:
      uri: ${MONGO_CONNECTION_STRING:mongodb://localhost:27017}
      database: ${MONGO_DATABASE_NAME:Products}

# Swagger configurations
swaggerBaseUrl: ${SWAGGER_BASE_URL:localhost:${server.port}}
